getwd()
setwd('C:/Users/zdt-pc/Dev/Github/iZDT/datamining-dp')
table <- read.csv('data/shopList.csv', sep =',',header = T)
head(table)
plot(table$deliverTime~table$sold)
plot(table$sold~table$extraService)
