getwd()
setwd('C:/Users/zdt-pc/Dev/Github/iZDT/datamining-dp')
table <- read.csv('data/shopList.csv', sep =',',header = T)
head(table)
plot(table$deliverTime~table$sold)
plot(table$sold~table$extraService)
#Statistic
sum(table$sold)
max(table$sold)
min(table$sold)
mean(table$sold)
range(table$sold)
range(table$star)
length(table$sold)
sort(table$sold, decreasing=T)
numCut <- cut(table$sold, c(-Inf, 0, 1000,3000,6000,9000,12000, Inf))
tapply(table$sold, table$star, sum)  #caclute sold sum of diffrent star
tapply(table$sold, table$brand, sum)
tapply(table$sold, table$extraService, sum)
deliverSold <- tapply(table$sold, table$deliverTime, sum)
tapply(table$sold, table$deliverTime, length)
mode(deliverSold)
sum(deliverSold)
sum(table$sold)
