table <- read.table('data/shopList.txt', header = TRUE, encoding = 'UTF-8')
topShop <- read.table('data/topshopList.txt', header = TRUE, encoding = 'UTF-8' )
#topShop <- read.csv('data/topshopList.csv', header = TRUE, encoding = 'UTF-8', sep =',' )
library(ggplot2)
#head(table)
ggplot(data=table,aes(x=star,y=sold,color=factor(brand))) + geom_point()
ggplot(data=topShop,aes(x=star,y=sold,color=factor(brand))) + geom_point()+geom_smooth()
total <- tapply(topShop$sold, topShop$extraService, sum)
pie(total)
